# Generated by Django 2.2 on 2020-10-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201004_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='start_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='start_Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
