# Generated by Django 2.2 on 2020-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201005_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
