# Generated by Django 2.2 on 2020-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_attendence_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=10, null=True),
        ),
    ]
