# Generated by Django 2.2 on 2020-10-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_attendence_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=20, null=True),
        ),
    ]
