# Generated by Django 2.2 on 2020-10-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_attendence_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='Assignments',
            new_name='Assignment',
        ),
    ]
