# Generated by Django 2.2 on 2020-10-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20201006_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='end_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='end_Time',
            field=models.TimeField(null=True),
        ),
    ]
