# Generated by Django 2.2 on 2020-10-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20201006_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='end_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='end_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
