# Generated by Django 2.2 on 2020-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20201006_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='end_Date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
