# Generated by Django 2.2 on 2020-10-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20201006_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='end_Date',
            field=models.DateField(blank=True, default='1111-11-11', null=True),
        ),
    ]
