# Generated by Django 2.2 on 2020-10-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20201006_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='Comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='Marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignments',
            name='Scored',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignments',
            name='files',
            field=models.FileField(upload_to='static'),
        ),
    ]
