# Generated by Django 2.2 on 2020-10-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20201006_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='Marks',
            new_name='Total_Marks',
        ),
    ]
