# Generated by Django 2.2 on 2020-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20201006_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='Submission',
            field=models.FileField(default=0, upload_to='static'),
            preserve_default=False,
        ),
    ]
