# Generated by Django 2.2 on 2020-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_assignments_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='Scored',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='Total_Marks',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
