# Generated by Django 2.2 on 2020-10-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20201006_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='Assignment',
            new_name='description',
        ),
        migrations.AddField(
            model_name='assignments',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
