# Generated by Django 2.2 on 2020-10-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20201006_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scored', models.PositiveIntegerField(null=True)),
                ('Comment', models.CharField(max_length=1000, null=True)),
                ('Submission', models.FileField(upload_to='static')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='Scored',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='Submission',
        ),
    ]
