# Generated by Django 2.2 on 2020-10-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20201006_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdetails',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StdSubmission', to='dashboard.Student'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='AssignDetails',
            field=models.ManyToManyField(to='dashboard.AssignmentDetails'),
        ),
    ]
