# Generated by Django 2.2 on 2020-10-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20201006_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentdetails',
            old_name='Comment',
            new_name='Remarks',
        ),
        migrations.AddField(
            model_name='assignmentdetails',
            name='Sub_Comment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
