# Generated by Django 2.2 on 2020-10-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20201006_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentdetails',
            old_name='Sub_Comment',
            new_name='Sub_Details',
        ),
    ]
