# Generated by Django 2.2 on 2020-10-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20201006_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentdetails',
            options={'verbose_name': 'AssignmentDetail'},
        ),
        migrations.AddField(
            model_name='assignments',
            name='status',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
