# Generated by Django 2.2 on 2020-10-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20201007_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='status',
            field=models.CharField(default='No Submission Yet', max_length=1000, null=True),
        ),
    ]
