# Generated by Django 2.2 on 2020-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20201007_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='status',
        ),
        migrations.AddField(
            model_name='assignmentdetails',
            name='status',
            field=models.CharField(default='No Submission Yet', max_length=1000, null=True),
        ),
    ]
