# Generated by Django 2.2 on 2020-10-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20201007_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
