# Generated by Django 2.2 on 2020-10-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20201008_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='Section',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
