# Generated by Django 2.2 on 2020-10-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_attendence_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdetails',
            name='Assignmnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StdAssigns', to='dashboard.Assignments'),
        ),
    ]
