# Generated by Django 2.2 on 2020-10-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_assignmentdetails_assignmnet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentdetails',
            old_name='Assignmnet',
            new_name='Assignment',
        ),
    ]
