# Generated by Django 2.2 on 2020-10-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20201010_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submission', models.FileField(upload_to='static')),
                ('Answers', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Answer',
            },
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='QuestionAnswers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='files',
        ),
        migrations.CreateModel(
            name='QuizDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Details', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(default='No Answered Yet', max_length=1000, null=True)),
                ('Remarks', models.CharField(max_length=1000, null=True)),
                ('Scored', models.PositiveIntegerField(null=True)),
                ('Ans', models.ManyToManyField(to='dashboard.Answer')),
                ('Quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyQuiz1', to='dashboard.Quiz')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StdQuiz', to='dashboard.Student')),
            ],
            options={
                'verbose_name': 'QuizDetails',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10, null=True)),
                ('Answers', models.CharField(max_length=1000, null=True)),
                ('Quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyQuiz2', to='dashboard.Quiz')),
            ],
            options={
                'verbose_name': 'QuestionAnswer',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='quizDetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyAns', to='dashboard.QuizDetails'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuestionAns',
            field=models.ManyToManyField(to='dashboard.QuestionAnswer'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuizDetail',
            field=models.ManyToManyField(to='dashboard.QuizDetails'),
        ),
    ]
