# Generated by Django 2.2 on 2020-10-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20201011_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Total_Marks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_Date',
            field=models.DateField(blank=True, default='1111-11-11', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='files',
            field=models.FileField(default=0, upload_to='static'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
