# Generated by Django 2.2 on 2020-10-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20201012_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
