# Generated by Django 2.2 on 2020-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='uplaod',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
