# Generated by Django 2.2 on 2020-10-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_quiz_uplaod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='uplaod',
            new_name='upload',
        ),
    ]
