# Generated by Django 2.2 on 2020-10-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20201012_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='Marks',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
