# Generated by Django 2.2 on 2020-10-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_questionanswer_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQANSWERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answers1', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000)),
                ('Quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyQuizAns', to='dashboard.Quiz')),
            ],
        ),
    ]
