# Generated by Django 2.2 on 2020-10-12 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_mcqanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='MCQAns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MCQAns', to='dashboard.MCQANSWERS'),
        ),
    ]
