# Generated by Django 2.2 on 2020-10-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_questionanswer_mcqans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqanswers',
            name='Quiz',
        ),
        migrations.AddField(
            model_name='mcqanswers',
            name='QuesAns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyQuizAns', to='dashboard.QuestionAnswer'),
        ),
    ]
