# Generated by Django 2.2 on 2020-10-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20201013_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='MCQAns',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='MCQAns',
            field=models.ManyToManyField(to='dashboard.MCQANSWERS'),
        ),
    ]
