# Generated by Django 2.2 on 2020-10-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20201013_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqanswers',
            name='Correct_Ans',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcqanswers',
            name='Answers',
            field=models.CharField(max_length=1000),
        ),
    ]
