# Generated by Django 2.2 on 2020-10-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20201014_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnsQs', to='dashboard.QuestionAnswer'),
        ),
    ]
