# Generated by Django 2.2 on 2020-10-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Review',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10, null=True),
        ),
    ]
