# Generated by Django 2.2 on 2020-10-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_quiz_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRADE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('Assignments', models.ManyToManyField(to='dashboard.Assignments')),
                ('Quizes', models.ManyToManyField(to='dashboard.Quiz')),
            ],
        ),
    ]
